// app/layout.tsx (or the relevant file)
import "./globals.css";
import NextAuthProvider from "./providers";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import QueryClientProviderWrapper from "@/components/QueryClientProviderWrapper";

export const metadata = {
  title: "Stock Glimpse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: any;
}) {
  return (
    <html lang="en">
      <body>
        <QueryClientProviderWrapper>
          <Header />
          <NextAuthProvider session={session}>{children}</NextAuthProvider>
          <Footer />
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
