import "./globals.css";
import NextAuthProvider from "./providers";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import QueryClientProviderWrapper from "@/components/QueryClientProviderWrapper";
import BackButton from "@/components/BackButton";

export const metadata = {
  title: "Stock Glimpse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryClientProviderWrapper>
          <NextAuthProvider>
            <Header />
            <BackButton />
            {children}
            <Footer />
          </NextAuthProvider>
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
